"""Assemble explicitly reviewed per-body findings; this does not infer semantics from names."""
from pathlib import Path
import json,hashlib
P=Path(__file__).parent
md=json.loads((P/'managed_tools_round5_metadata.json').read_text())
vr=json.loads((P/'managed_tools_round5_verification.json').read_text())
M={m['idaSyntheticAddress']:m for m in md['methodBodies']}
findings=[]
def add(addr,finding,limitation):
    m=M[addr];edges=[e for e in vr['incomingCallEdges'] if e['targetToken']==m['token']]
    table=[dict(table=t['startField'],slot=e['slot'],rva=e['rva']) for t in vr['initializerTables'] for e in t['entries'] if e.get('method',{}).get('token')==m['token']]
    findings.append(dict(addr=addr,Domain='cil',Name=m['display'],MethodDef=m['token'],OriginalHeaderRva=m['headerRva'],
        CodeBytes=m['codeSize'],CodeSha256=m['codeSha256'],Finding=finding,
        Evidence=['managed_tools_round5_evidence.json','managed_tools_round5_metadata.json','managed_tools_round5_cil_bytes.json','managed_tools_round5_verification.json'],
        DirectCallers=[dict(addr=e['callerSyntheticAddress'],token=e['caller']['token'],name=e['caller']['name'],ilOffset=e['ilOffset'],opcode=e['opcode']) for e in edges],
        InitializerTableReferences=table,
        Limitations='Synthetic CIL address, not a native RVA or process-call address. '+limitation))
add('0x3390','Constructs ModuleLoadExceptionHandlerException with the fixed initialization/cleanup failure message, original exception and cleanup exception, then throws it.',
    'This preserves both failures; it does not recover initialization or display a game dialog.')
add('0x33a0','Constructs and throws ModuleLoadException from the supplied message.', 'The final ret is unreachable after throw; no cleanup occurs here.')
add('0x33b0','Constructs and throws ModuleLoadException from the supplied message and inner exception.', 'Cleanup is the caller\'s responsibility.')
add('0x33c0','Loads the ModuleUninitializer singleton and forwards the supplied EventHandler to AddHandler.', 'No null, duplicate or handler-lifetime validation is added by this wrapper.')
add('0x33d0','Reads the native 16-byte GUID as DWORD, two WORDs and eight bytes and calls System.Guid\'s component constructor.', 'The supplied native pointer must reference 16 readable bytes; this is not a parser for an arbitrary textual GUID.')
add('0x3420','Obtains a CLR runtime COM interface using the two original cb2f6722/cb2f6723 GUID records; runtime acquisition exceptions become HRESULTs. On success, calls COM slot+0x68 to retrieve the default-domain IUnknown, releases the host through slot+0x10 and returns the HRESULT.',
    'The output pointer is a native COM reference. This is runtime-host interop, not a game object or an editor window. The release is explicit after the call, not a general exception-protected wrapper for arbitrary COM implementations.')
add('0x3480','Calls Release through IUnknown vtable+0x10 and discards the reference-count return.', 'The argument must be a valid non-null COM interface; no ownership check or null guard exists.')
add('0x3490','Calls __get_default_appdomain, throws for a negative HRESULT, converts the returned IUnknown with Marshal.GetObjectForIUnknown and casts to AppDomain. A finally clause releases the native IUnknown after conversion.', 'The returned managed AppDomain object and the released native reference have different ownership. The fallback null after ThrowExceptionForHR is not a successful domain result.')
add('0x34d0','Obtains the CLR runtime interface for the 90f1a06c/90f1a06e GUID pair, gets the default AppDomain ID and invokes COM slot+0x40 with domain ID, native callback and cookie. Negative HRESULTs become exceptions; finally releases the COM host.', 'The callback must be a valid CLR-compatible native thunk. Passing a synthetic IDA CIL address would violate this contract.')
add('0x3540','Returns whether the native DllMain-reason value is greater than 1 using an unsigned comparison.', 'This is the exact gate used by managed native initialization; it does not establish general thread safety for other engine calls.')
add('0x3550','Boxes Int32.MaxValue, passes it to GC.KeepAlive and returns zero.', 'Its useful role is a trivial default-domain callback whose invocation forces the module path; it changes no renderer or game state itself.')
add('0x3570','Caches whether any nonzero QWORD exists in [__xc_mp_a,__xc_mp_z). TriBool2 triggers the scan, -1 records true and 0 records false.', 'These QWORD values are later resolved as managed method tokens. This method only checks presence and does not execute or validate them.')
add('0x35c0','Caches whether the native initializer ranges [__xi_a,__xi_z) or [__xc_a,__xc_z) contain a nonzero QWORD, using TriBool2/-1/0.', 'It checks presence, not successful initialization, code identity or entry-point safety.')
add('0x3640','Requests default-domain initialization if per-process initializers exist but have not run, or native initializers exist while native initialization is false and startup state is zero.', 'The native condition includes startup-state gating; this is not simply the inverse of one initialized bit.')
add('0x3670','Returns the process-level DefaultDomain.Entered flag.', 'This tests whether default-domain initialization was entered, not whether every initialization stage succeeded.')
add('0x3680','Loads the native __unep thunk for DoNothing and asks DoCallBackInDefaultDomain to invoke it with a null cookie.', 'The original thunk field stores native VA0x140579E20; the CIL body address0x3550 is not interchangeable with it.')
for addr,field in [('0x3690','CurrentDomain.Initialized'),('0x36a0','CurrentDomain.Uninitialized'),('0x36b0','CurrentDomain.IsDefaultDomain'),('0x36c0','CurrentDomain.InitializedVtables'),('0x36d0','CurrentDomain.InitializedNative'),('0x36e0','CurrentDomain.InitializedPerProcess'),('0x36f0','CurrentDomain.InitializedPerAppDomain')]:
    add(addr,'Stores zero into '+field+' and returns. Its MethodDef is a nonzero entry in the per-AppDomain initializer table.', 'This three-instruction body initializes one managed static field; it performs no native reset or cleanup.')
add('0x3700','Sets the GC-rooted failure-stage message, sets vtable progress to1, runs _initterm_m over __xi_vt_a..__xi_vt_z, then records progress2.', 'This binary\'s stored vtable initializer range contains one zero sentinel and no nonzero tokens. The generic stage machinery is present even though this range has no work.')
add('0x3730','Sets the default-AppDomain failure-stage message and calls DefaultDomain.Initialize.', 'The actual cross-domain transition occurs in the callback helper; this body provides stage context only.')
add('0x3750','Sets the native failure-stage message, initializes the security cookie and marks DefaultDomain.InitializedNative. It aborts when managed entry is unsafe or startup is already in-progress. From state0 it sets state1, runs _initterm_e and then _initterm, records state2 and native-from-cctor/progress completion.', 'A nonzero _initterm_e result throws a module-load exception. InitializedNative is set before the native initializer table completes; that flag alone is not proof of success.')
add('0x37e0','Sets the per-process failure-stage message and progress1, creates the managed process exit table, executes __xc_mp_a..__xc_mp_z via _initterm_m, then sets progress2 and DefaultDomain.InitializedPerProcess.', 'The return from _initatexit_m is discarded. The original table contains37 nonzero managed tokens, including ATL initialization and scratch-pad initialization entries.')
add('0x3820','Sets the per-AppDomain failure-stage message and progress1, calls _initatexit_app_domain, executes __xc_ma_a..__xc_ma_z and records progress2.', 'The exit-table initialization return is discarded; this binary\'s seven nonzero table entries clear the seven CurrentDomain fields individually.')
add('0x3850','Sets the uninitializer failure-stage message, creates an EventHandler for LanguageSupport.DomainUnload and registers it with ModuleUninitializer.', 'Registration is part of the final initialization stage; this body does not unload anything immediately.')
add('0x3870','Records whether the current AppDomain is default and sets the process Entered flag. It acquires the native startup lock with the current fiber ID, tolerates recursive acquisition by the same ID and retries others after Sleep(1000). Under that lock it initializes vtables and default-domain native/per-process state; another domain can request default-domain initialization after releasing the lock. It then initializes per-domain state, marks the domain initialized and registers its uninitializer.', 'Lock release is protected by finally and occurs only for the outer owner. This orchestrates runtime/module startup, not a callable feature toggle; calling it again manually would violate the compiler-owned lifecycle.')
add('0x3940','Delegates per-AppDomain teardown to _app_exit_callback.', 'It does not independently guarantee once-only execution; DomainUnload supplies that guard.')
add('0x3950','Runs the process exit callback and clears InitializedPerProcess. If native initialization was performed by the module cctor, calls _cexit, clears native startup state and the ownership flag. Finally clears InitializedNative and returns zero.', 'The ownership flag prevents this path from treating all native startup as cctor-owned. Callback exceptions can interrupt later cleanup steps.')
add('0x3980','If the default domain was entered, uninitializes directly when already in that domain; otherwise invokes the native default-domain teardown thunk with a null cookie through DoCallBackInDefaultDomain.', 'The thunk field stores native VA0x140579E90. No action occurs when the Entered flag is false.')
add('0x39b0','Skips uninitialized domains and uses Interlocked.Exchange(Uninitialized,1) as an exactly-once gate. The first entrant decrements the shared domain count, tears down the current domain and, when the count becomes zero, uninitializes default-domain/process state.', 'If teardown throws, the once flag and decremented count are not rolled back. The guard belongs to this handler, not to ModuleUninitializer\'s stack enumerator.')
add('0x39e0','Failure cleanup decrements the shared domain count, runs per-domain teardown and tears down process/default-domain state when last. Cleanup exceptions are wrapped together with the original initialization exception; the non-Exception catch supplies a null secondary exception.', 'This is the failed-initialization path; callers must only use it after the successful domain-count increment. It is not a retry or rollback of arbitrary engine initialization.')
add('0x3a20','Constructs the gcroot<String> storage at the supplied LanguageSupport address and returns that address.', 'Original ClassLayout gives LanguageSupport8 bytes; the storage contains a GCHandle token, not inline string text.')
add('0x3a30','Invokes the gcroot<String> destructor at the LanguageSupport address.', 'The object must own a live GCHandle; there is no independent double-free guard here.')
add('0x3a40','Sets the initial failure-stage string and uses a constrained region to increment AllDomains.Count and record that increment. It calls _Initialize; exceptions trigger Cleanup only after the count increment, then become ModuleLoadException carrying the current stage and original exception.', 'An exception raised by Cleanup can replace the ordinary wrapper with the nested-failure exception. This body implements bookkeeping on failure, not a guaranteed successful recovery.')
add('0x3ab0','The module cctor constructs a local LanguageSupport, calls its Initialize, and destroys it on success; its unwind clause also destroys it through the C++ unwind helper.', 'This is the compiler-owned module entry lifecycle. Direct invocation from an arbitrary worker thread is not an activation contract for developer windows.')
add('0x3ae0','Converts the stored pointer-sized token into a GCHandle and reads its Target as the rooted string.', 'This retrieves a managed reference; it does not expose a stable native string buffer.')
add('0x3b00','Converts the stored token into a GCHandle, replaces Target with the supplied string and returns this.', 'It reuses the existing handle rather than allocating or pinning a new string for every stage change.')
add('0x3b20','Reconstructs the GCHandle, calls Free, then writes zero to the stored token.', 'A zero token is the post-destruction state; the body does not test it before Free, so repeated destruction is not supported.')
add('0x3b40','Allocates a GCHandle whose initial Target is null, converts the handle to IntPtr and stores its pointer-sized value in this.', 'No explicit pinned-handle overload is used. The handle preserves reachability, not a native data layout for the string.')
for addr,desc in [('0x3b60','the provided destructor(this)'),('0x3b80','the provided deleting-destructor callback(this)'),('0x3ba0','the provided vector-destructor callback(array,size,count,destructor)')]:
    add(addr,'Invokes '+desc+' through calli. The exception filter obtains native exception pointers and calls __FrameUnwindFilter; the handler is selected only when that native filter allows it.', 'This is compiler unwind glue. It neither validates the callback nor proves all exceptions are swallowed; __FrameUnwindFilter governs the exceptional edge.')
add('0x3bc0','Returns null when the global at-exit GCHandle token is zero; otherwise reconstructs and boxes that GCHandle.', 'The result is a boxed handle value used by the other lock helpers, not the Monitor object itself.')
add('0x3bf0','Calls _lock_Set only when the global handle token is zero.', 'An already constructed handle is left unchanged; this helper adds no interlocked initialization protocol.')
add('0x3c00','Allocates and stores a GCHandle for the supplied lock object when none exists; otherwise changes the existing handle Target.', 'Target replacement is not itself synchronized here. Compiler startup sequencing and surrounding ownership are required.')
add('0x3c50','Returns the existing lock GCHandle.Target, or null when no handle exists.', 'This getter alone does not acquire a monitor or prolong a separate native object lifetime.')
add('0x3c70','If the lock handle exists, frees it and clears the global token.', 'The helper does not acquire the monitor before releasing the handle; its callers must provide valid teardown sequencing.')
add('0x3c90','Returns whether _lock_Get yields a non-null object.', 'A nonzero handle whose Target is null is considered uninitialized.')
add('0x3ca0','Creates a new Object and lock handle if needed, resets the reference count to zero in that case, then increments the ordinary int32 reference count.', 'The increment is not Interlocked and this body does not lock itself. It is lifecycle bookkeeping, not a general concurrent reference-counted primitive.')
add('0x3cd0','Decrements the ordinary int32 lock reference count and destroys the lock handle exactly when the result is zero.', 'No underflow check or concurrent atomic decrement is present; balanced compiler-managed calls are assumed.')
add('0x3cf0','Calls Monitor.Enter on the object returned by _lock_Get.', 'A missing/null target can fail; this entry does not first check IsInitialized.')
add('0x3d00','Calls Monitor.Exit on the object returned by _lock_Get.', 'The caller must own that monitor on the current thread; this body does not track ownership.')
add('0x3d10','Returns false if the at-exit lock is uninitialized; otherwise enters it and returns true.', 'The check and Monitor.Enter are separate calls, so safe teardown sequencing remains an external precondition.')
add('0x3d30','Returns false if the at-exit lock is uninitialized; otherwise exits it and returns true.', 'It does not validate current-thread ownership before Monitor.Exit.')
add('0x3d50','Adds a lock reference and reports whether the resulting lock object is initialized.', 'Reference addition may throw while allocating a managed object/handle.')
add('0x3d60','Drops one at-exit lock reference by calling RemoveRef.', 'This wrapper adds no extra exception or lifetime handling.')
add('0x3d70','Registers one encoded callback under the at-exit monitor. It rejects a null supplied value or unavailable lock, decodes begin/end, grows full tables, appends an8-byte slot, advances end and re-encodes the table pointers. Normal growth doubles up to an additional4096 bytes. Its OutOfMemoryException fallback asks ReAllocHGlobal for capacity*8+12 bytes but advertises capacity+4 pointer slots; the outer OOM catch returns-1 and finally releases the monitor.', 'The fallback has a static allocation-size/capacity mismatch on this64-bit build. With capacity32, requested268 bytes are treated as36 slots/288 bytes. Reaching it requires the larger allocation to throw OOM and the smaller allocation to succeed; actual allocator slack and runtime reachability were not tested. Both allocation sizes also narrow through IntPtr(int32).')
add('0x3e90','Decodes the process exit table and executes callbacks from the end. Each slot is changed to encoded-null before calli; changed global begin/end values after a callback cause it to resume from the new end. It frees the table and releases the lock reference after normal completion.', 'There is no finally covering callback execution/free here. A callback exception can prevent table free and lock-reference release; the body does not reset table globals for repeated invocation.')
add('0x3f40','Acquires an at-exit lock reference, allocates256 unmanaged bytes and encodes the same pointer into begin/end with capacity32. Returns1 on lock success and0 otherwise.', 'Allocation failures propagate; the return reports this initialization attempt rather than a validated table of callbacks.')
add('0x3f80','Calls _atexit_m and returns the original function pointer unless registration returned-1, in which case it returns null.', 'The result is a callback pointer/status convention, not an invocation of that function.')
add('0x3f90','Encodes the supplied callback pointer and forwards it with the process-global capacity/end/begin fields to _atexit_helper.', 'Pointer encoding is supplied by the KERNEL32 P/Invoke declaration, not by an executable local CIL body.')
add('0x3fb0','On successful lock-reference acquisition, allocates256 bytes and initializes the per-AppDomain begin/end/capacity32 fields. The body returns1 even if the lock-acquisition result was false.', 'Therefore its constant success return cannot be used as proof that fields were initialized; allocation exceptions still propagate.')
add('0x3ff0','Runs per-AppDomain callbacks backwards, clearing each slot to encoded-null before calli and rereading table pointers after callbacks to handle registration/reallocation. Its finally always frees the decoded table and drops the lock reference once this table-processing path is entered.', 'Callback exceptions stop the remaining callbacks even though finally frees the table. Table globals are not zeroed; the outer DomainUnload once gate is required.')
add('0x40c0','Calls _atexit_m_appdomain and returns the supplied callback unless registration returns-1, then returns null.', 'This is the AppDomain version of the pointer/status wrapper; no callback is executed here.')
add('0x40d0','Encodes a callback and passes the per-AppDomain capacity/end/begin references to _atexit_helper.', 'It shares the same allocator/fallback behavior as the process-global registration path.')
add('0x4110','Starts at array+size*count and invokes destructors backwards, decrementing the remaining count before each call. A finally invokes __ArrayUnwind on the still-undestroyed prefix if the loop did not complete.', 'Arithmetic and pointers are trusted compiler inputs; there is no bounds or multiplication-overflow validation for externally supplied arrays.')
add('0x4150','Reads the native exception code and calls terminate for0xE06D7363, otherwise returns0 to the filter.', 'This handles a C++ exception during array unwinding; returning0 does not mean a general exception was handled.')
add('0x4170','Destroys a remaining array prefix backwards using the supplied count/stride/destructor. Its filter delegates secondary exceptions to ArrayUnwindFilter.', 'The helper is for exceptional cleanup, with compiler-provided valid array state; it is not a safe arbitrary-pointer deletion API.')
add('0x41a0','Sign-extends the int32 element count to int64 and forwards array, stride, count and destructor to __ehvec_dtor.', 'Negative counts are not rejected here; normal compiler-generated array counts are the intended inputs.')
add('0x41b0','Scans a native QWORD function-pointer range, skips null entries and calls each as a cdecl int() initializer until one returns nonzero, which it returns; returns0 after successful completion.', 'The original __xi range has3 nonzero entries. This function trusts both range and pointers and does not roll back previously run initializers.')
add('0x41e0','Scans a native QWORD function-pointer range, skips nulls and calls each cdecl void() initializer in ascending order.', 'The original __xc range has4653 nonzero entries; this report records those pointer values without claiming the full semantics of every target.')
add('0x4200','Obtains this managed type\'s Module via its RuntimeTypeHandle and returns the ModuleHandle.', 'This supplies the metadata-resolution context, not a Win32 module base or native HMODULE.')
add('0x4220','Scans QWORD slots in a managed initializer range, skips zero, resolves each nonzero value with ThisModule.ResolveMethod and invokes the result through a managed calli, discarding the pointer-sized return.', 'The slots are method tokens stored in8-byte cells. Treating them as preexisting native function pointers would misinterpret the format.')
add('0x4250','Truncates the supplied slot value to int32, resolves it with ModuleHandle.ResolveMethodHandle and returns RuntimeMethodHandle.GetFunctionPointer().ToPointer().', 'It does not validate the token table/rid before asking the CLR; resolution may throw and the returned pointer is runtime-specific.')
add('0xc010','Constructs the native-render-host Form, retains the supplied AppInterface pointer, initializes its state, runs32 no-op FVECTOR2 constructors and requests up to32 resolutions. It selects the second vector when the returned count is at least1, otherwise the first. It constructs child controls, installs14 lifecycle/input/timer event handlers, records the singleton, uses the supplied title, sets opacity0, loads icon resource101 and creates the window handle. A fault clause disposes the base Form if construction fails.', 'The local-array header does not request InitLocals. Fresh native evidence shows the vector constructor writes nothing and resolution enumeration normally returns the number written. If only one vector is written, the selected second vector is uninitialized along this path. The fallback enumerator can return1 after writing multiple vectors, so returned1 alone is insufficient to demonstrate the fault. No asset editor widgets or model/animation payload loading occur here.')
findings[-1]['Evidence']+=['managed_tools_round5_native_resolution.json','managed_tools_round5_native_enumerate_asm.json']
add('0xc640','Creates a component container and Timer, then a200x50 red panel anchored top/right and a blue fill-docked mouse panel, wiring their mouse handlers. Sets ClientSize from initialSize, a black background and20-pixel padding, adds both panels and resumes layout without a layout pass.', 'This is a window/render-surface skeleton. The body does not set Timer.Enabled or Interval, load textures, create animation controls, or implement a standalone preview editor.')
for addr,typ,args in [('0xfb50','CrtImplementationDetails.Exception','SerializationInfo and StreamingContext'),('0xfb60','CrtImplementationDetails.Exception','message and inner exception'),('0xfb70','CrtImplementationDetails.Exception','message'),('0xfb90','ModuleLoadException','SerializationInfo and StreamingContext'),('0xfba0','ModuleLoadException','message and inner exception'),('0xfbb0','ModuleLoadException','message')]:
    add(addr,'Initializes '+typ+' by forwarding '+args+' directly to the corresponding System.Exception constructor.', 'No engine cleanup, UI, retry or custom field processing occurs in this constructor.')
add('0xfbd0','Initializes the module-load exception from serialization data, retrieves the NestedException key as System.Exception and stores it through the property setter.', 'It preserves the secondary exception for diagnostic serialization; absent or incompatible serialized data can throw.')
add('0xfc00','Calls the ModuleLoadException(message,inner) constructor and stores the separately supplied nested exception.', 'The two exception references represent original initialization failure and secondary cleanup failure; neither is executed or handled by this constructor.')
add('0xfc10','Returns the backing field holding the nested cleanup exception.', 'A null result is allowed and carries no independent success/failure state.')
add('0xfc20','Stores the supplied value in the nested-exception backing field.', 'This is an ordinary managed reference assignment with no cleanup or validation.')
add('0xfc30','Formats type, message, InnerException.ToString and NestedException.ToString using the embedded four-argument template with separate primary and nested sections; null fields become empty strings.', 'This prepares diagnostic text only. It does not show a dialog, log to a file or restore module state.')
add('0xfcd0','Calls base Exception.GetObjectData, then adds NestedException with the declared System.Exception type to SerializationInfo.', 'The code serializes a managed diagnostic field; it defines no game-save or portable asset format.')
add('0xfd10','In a constrained region, enters the static monitor, prepares the supplied delegate and pushes it onto the inherited Stack; finally releases the monitor when acquired.', 'Duplicates are not removed. Preparing a delegate is not executing it, and callers retain responsibility for handler validity.')
add('0xfd50','Creates the shared monitor object and then a ModuleUninitializer singleton.', 'Singleton construction registers events; this type initializer does not run cleanup handlers immediately.')
add('0xfd70','Constructs the Stack base and subscribes the same SingletonDomainUnload instance method to both CurrentDomain.DomainUnload and CurrentDomain.ProcessExit.', 'Both events can reach the same stack. This class itself provides no once flag, so handlers such as LanguageSupport.DomainUnload must guard repeated teardown.')
add('0xfda0','Holds the static monitor while enumerating the handler Stack and invoking each EventHandler with the event source/args. Nested finally clauses dispose an IDisposable enumerator and release the monitor.', 'It enumerates rather than pops/clears the stack. No per-handler catch permits continuing after a failing handler; Stack enumeration supplies reverse registration order.')
add('0xfe20','Forwards SerializationInfo and StreamingContext to System.Exception\'s deserialization constructor for the OpenMP-specific exception type.', 'The body does not itself detect multiple AppDomains or enforce an OpenMP restriction.')
add('0xfe30','Calls the parameterless System.Exception constructor for the OpenMP-specific exception type.', 'There is no custom text or OpenMP state check in this body; the type name alone is not evidence of an active engine restriction.')
assert len(findings)==98 and {f['addr'] for f in findings}==set(M)
report=dict(Date='2026-10-04',Status='Read-only static research; no product change or runtime activation.',SourceSha256=md['sourceSha256'],
    Scope='98 previously unclaimed executable CIL bodies: native-render-host construction plus CLR/default-domain/exit-list/unwind lifetime. Two RVA0 P/Invoke placeholders are separately documented and excluded.',
    Counts=dict(cilBodies=98,fullIlInstructions=1953,originalIlBytes=4669,exceptionClauses=24,directMethodDefCallerEdges=158),
    AddressPolicy='addr in Findings is synthetic CIL. OriginalHeaderRva identifies stored IL, not callable machine code. Explicit native VAs are labeled in evidence; do not add imagebase to synthetic addresses.',
    Findings=findings,BodylessImportsEvidence='managed_tools_round5_bodyless_imports.json',
    MainResults=['No additional model, motion or texture editor was found in the two remaining GUI construction bodies.',
        'The constructor can read an unwritten second resolution vector when only one eligible mode was actually written.',
        'The64-bit OOM reallocation fallback grows by12 bytes but advertises4 extra pointer slots.',
        'The CLR bootstrap traverses managed-token tables and native-pointer tables using distinct call conventions; process and AppDomain teardown are separate.',
        'The per-domain unload handler is once-guarded, while the event stack is retained and registered for both DomainUnload and ProcessExit.'],
    Use='Useful for mixed-mode loader diagnosis, safe offline metadata inspection and understanding why direct construction/unload of the old developer UI is not an isolated asset-preview operation.',
    Limitations=['No runtime reachability, allocation-failure reproduction, display-mode manipulation or game/UI execution was attempted.',
        'Native initializer pointer inventory is not a semantic claim for4653 individual targets.',
        'Caller data includes exact direct MethodDef operands and stored initializer-table references; dynamic/native callers are not exhaustive.',
        'No new trainer button is justified by these bodies alone. An offline startup/lifetime map is a possible later tooling feature, not an implemented product change.'])
(P/'managed_tools_round5_report.json').write_text(json.dumps(report,indent=2),encoding='utf-8')
print('Saved',len(findings),'explicit CIL claims.')
