"""Build round6 research reports from reviewed statements and verified fresh captures."""
from pathlib import Path
import hashlib,json
ROOT=Path(__file__).resolve().parents[3]
OUT=ROOT/'work/trainer/research'
verification=json.loads((OUT/'renderer_round6_verification.json').read_text(encoding='utf8'))
captures={x['addr'].lower():x for x in verification['captures']}
findings=[
('124fe0','Native display request takes GX inRCX, pointer to two float32 values inRDX and mode inR8D. Under resizeCS+31432 it copies all needed values into GX request fields and retains no caller buffer. Mode0 performs float32 16:9 fit/truncation; mode2 keeps dimensions unchanged; mode1 enumerates accepted monitor modes and selects exact-or-first. It writes pending dirty by comparing against active mode/dimensions.','There is no completion/result token. Mode1 inherits11C970 recursion on an empty mode set; mode0/2 do not call enumeration. Native allocation/device failures occur later.'),
('124fb0','Public pointer/mode wrapper preservesRCX/RDX arguments around the GX singleton getter, then tailcalls124FE0 with GX inRCX, dimensionsRDX and modeR8D. Settings callers use this exact request route.','Prefer already-leased GX plus124FE0 for a trainer; invoking the getter could initialize a missing singleton.'),
('506c90','Maps supplied settings mode0 to native exclusive mode1, settings1 to native maximized mode2, other values to native windowed0; loads unsigned16 dimensions from Settings+6/+8 and calls124FB0.','This callback uses loaded dimensions rather than supplied custom dimensions. It does not itself validate arbitrary settings mode values.'),
('506d10','Loads Settings+4 mode and+6/+8 dimensions and repeats the same native1/2/0 mapping before124FB0. This is a narrow loaded-resolution reapply entry.','No completed GPU-resize status is returned; fullscreen enumeration remains a dependency.'),
('505d00','ApplyAll routes screen mode/dimensions through124FB0 after reading settings. It also applies brightness, color vision, input mappings, frame rate, language and four audio levels.','It is overbroad for a resolution-only trainer action and can affect unrelated runtime controls.'),
('11c970','Enumerates current-window monitor display modes, rejects width<800 or height<600, optionally rejects non16:9 modes, sorts/deduplicates and copies at most caller capacity float pairs. If nothing is copied, recursively calls itself with filter0 and the same capacity, then reports1.','No terminal case was found for an empty unfiltered mode set or zero capacity. This proves a native pathological recursion path, not its occurrence on a normal monitor.'),
('124970','WndProc-oriented size/fullscreen path treats width=-41267 as a fullscreen command/query, otherwise handles IsZoomed/client-size fallback and queues underCS31432. It can alter active fullscreen1046 before enteringCS.','This route is not a clean generic trainer resize API; negative sentinel dimensions have unrelated semantics and active-field access prevents treating all mode writers as one atomic request transaction.'),
('10eb40','Window procedure routes selected window size/fullscreen messages through124970 and handles close/activation state. The procedure is registered in11D0A0.','Window callbacks can be reentered during native ShowWindow/SetWindowPos. Keep actual resizing in the native frame-consumption path.'),
('119e90','At normal begin-frame, consumes pending20-byte resize request underCS31432; outside thatCS, fence-waits129560, releases119890, sets transition1072=2, adjusts window123020, rebuilds117FD0, clears transition and refreshes viewport/scales. Successful resize resets30556 and mainMSAA to0/1sample. Otherwise computes native adaptive maximum from1108 and vendor flag1224, calls113B80 and applies changed result through114D30.','This routine is frame-internal and must not be used as a trainer refresh call. Its full control flow establishes the proposed decision interception point11A14F.'),
('123020','Pre-resize mode handling restores or maximizes the native window. For ordinary window mode0 it bounds16:9 dimensions against cached primary-screen width/height and exits fullscreen if needed; mode2 maximizes; mode1 handles an existing maximized window.','Cached primary metrics need not equal the active monitor work area. This is not arbitrary-aspect/internal-resolution scaling.'),
('117fd0','Rebuild selects fullscreen1088/1092, zoomed client rect or active window dimensions;1119B0 negotiates allocation and dimensions. It updates native window geometry, resizes/recreates swapchain, recreates main/depth/resolve descriptors and previous-frame resources. Fullscreen SetFullscreenState unavailability schedules a60-unit retry countdown underCS31432.','COM operations are not fully checked/rolled back. Native geometry callbacks and device-loss behavior remain outside a static guarantee. Do not call directly from a post-Update handler.'),
('1119b0','Clamps each requested integer dimension to at least1, records float request1080/1084, invokes124B50 with mutable sample capability1108 and dimensions, then commits actual width/height8/12 and floats16/20.','Requested/actual dimensions can differ. The caller does not use124B50 HRESULT as a transactional guard before storing dimensions.'),
('124b50','Negotiates shared framebuffer heap using cached local budget minus usage minus776MiB,4MiB alignment, native allocation estimator and capability ceiling retained at heaprecord+36. It may halve sample count, halve dimensions, use a fallback dimension pair, or later raise capability toward the retained maximum.','1108 is allocation state, not a user preference. The unsigned subtraction/cache can be implausible under low budgets and is not continuous freeVRAM measurement.'),
('1145b0','Computes placed-resource requirements using D3D12 allocation-info queries and maximum native/4MiB alignments, main color/depth plus auxiliary alias regions and a2048x1088 color region. The sample descriptor is threaded into main and selected auxiliary descriptions.','This is evidence that sample count and heap capacity are coupled; it does not include all textures or guarantee future allocation success.'),
('117ef0','Releases previous heap, stores allocation bytes, creates a new native heap with4MiB alignment and flags132; success is based on the COM result.','The old heap is already released before a failure; no rollback lease is provided.'),
('124060','Device initialization queries adapter description; DWORD at description+256==0x1002 setsGX1224. It probes color format87 sample counts8/4/2/1, records supported count/quality1108/1112, creates heaps/command queues/fence packets and initial pending resolution.','1224 is vendor-dependent policy, not the user AA toggle. A raw write can also affect creation of an auxiliary command-list path.'),
('113b80','Adaptive decision ABI is historyRCX, intervalEDX, float budgetXMM2, currentR9D, min/max stack args. It decreases by2 on low headroom bounded by min and raises by1 after30 good samples bounded by max. Cooldown/middle band checks current against max at113BED and returns min on excess. However1140EB jumps to1145A1 and returns current without max checking when current headroom is high but a history sample fails the sustained-good test.','Corrects earlier universal-bound shorthand and this round preliminary cooldown/middle-band explanation after independent ASM review. Lowering1108 alone is not a reliable immediate cap; the unbounded early-history-return path is the precise counterexample.'),
('114d30','Reads target selectorEDX and exponentR8D, computes32-bit1<<CL, writes selected framebuffer+160 when changed, then recreates existing color/depth resources11B4F0/11B290. Main0, resolve5, auxiliaries1..4 and negative=current are native selectors.','No lock, fence, range check or rollback. Only exponent0..3 belongs to the proved sample/PSO pipeline; raw shift semantics do not authorize wider inputs.'),
('110820','Recorded closure reads target+8 and GX+16. For auxiliary target1 it first matches sample count to currentGX30556 through114D30, then ensures its color resource via11B4F0.','AA affects an auxiliary target as well as main0; bypassing native decision/replay bookkeeping can desynchronize this closure.'),
('128100','Begin-recording clears state and captures timing. With22944==0 it runs119E90 then shifts old30564 into30560 and current30556 into30564. With replay active it restores indexed historical exponent30564+4*index and calls114D30 if different.','A forced policy must run before the native normal branch commits history. Post-frame writes to30556 do not preserve this behavior.'),
('120ed0','Sets replay22944=1 before128100, replays captured closures and interpolated state, finishes128260, then clears22944. It selects one of two native closure histories.','Replay bypasses119E90; proposed AA policy must leave historical replay untouched rather than demanding one sample count during every intermediate frame.'),
('128260','Closing a normal interval restores exponent30564 before1219F0/submission, waits/collects completed GPU work and updates frame rings. It later collects each framebuffer resource pool.','Do not intercept114D30 globally: this valid historical restoration is part of the native pipeline.'),
('1219f0','Uses current exponent30556 versus older30560 plus native replay/pass state to choose previous-frame/resolve handling, then records fillScreen/FlushFrameBuffers work and advances command fences.','An AA override must preserve historical values and let this branch select its normal path; no new shader edit is necessary.'),
('128470','Holds presentation mutexGX30848 while closing current work, processing native fullscreen keyboard request, completing/replaying, collecting deferred resources and starting128100 for the next interval; unlocks before final application call.','Proves outer-mutex-before-resizeCS order. A trainer can queue a short native request hereafter on the application thread, not execute a separate render pass.'),
('1287d0','Timing/presentation worker takes the same outer mutex around replay120ED0 or closing128260, but native Present/fence/timing work can also occur outside that lock.','Outer mutex alone does not prove the GPU/Present is idle. The worker replay path sets22944 and does not execute the normal119E90 policy call.'),
('128450','Gets GX singleton and tailcalls128470. Its caller105E10 forms the normal timing/render facade.','Not a safe trainer operation: it closes/submits/rebuilds native frame state.'),
('105e10','Calls128450, performs renderer-side12BA80 and SteamPlatformTick. Its known callers include timing tasks154740/1548E0 and an application adapter.','This proves normal frame reachability, not an independent callable renderer initialization contract.'),
('1548e0','The native timing task updates game timing and calls105E10 in its normal frame path, establishing the gameplay-task route into128470/128100/119E90.','The proposed policy also needs application-thread identity; gameplay scene state is not a renderer lifetime guard.'),
('129560','Increments/signals the provided queue/fence packet, waits indefinitely if completion is behind the new value, then logs the CPU wait under historyCS. Resize119E90 uses the main packetGX31480 before releasing resources.','The native wait can block on driver/device failure; trainer request should queue and let this native path own synchronization.'),
('129130','Waits for an already scheduled fence target using SetEventOnCompletion and an infinite event wait, returning that target.129180 uses it before mapping completed GPU timing.','A completion getter can block; never call it to make a trainer snapshot fresh.'),
('119890','Releases tracked previous-buffer descriptors, invokes framebuffer virtual release for targets0..4 and clears color/depth pools; its resize flag preserves the separately managed frame-texture pool.','Requires caller GPU completion and valid virtual objects. It is not a user cache-clear action.'),
('119630','Clears each of64 pool entries, releases occupied COM pointers and resets descriptor/reference tracking via native slot cleanup.','Safe lifetime comes from resize/shutdown fence discipline, not this helper.'),
('11af70','Finds descriptor-matching64-slot resources or first empty COM slot, then associates it with native ownership through125AA0. Returnsfalse both for existing-key reuse and no-free-slot.','The boolean is not a generic allocation success status. A direct114D30 caller cannot assume resource creation succeeds from that result.'),
('125aa0','Nonzero frame context receives a pool-slot ownership reference; without a context, updates per-target current and historical slot indices, with separate tracking for sampled targets.','These references retain old descriptors during replay. No trainer-owned resource pointer should be retained or purged.'),
('123c60','Pool collector activates when fewer than10 slots are empty; excludes swapchain target5, tracked current/sample/history indices and entries with nonempty context ownership.','AA resource changes consume/cache multiple sample variants. Fixed policy must reuse this collector and not release previous variants manually.'),
('117ac0','Initializes framebuffer sample descriptor from the negotiated pair, assigns dimensions, reserves aligned color heap offset and creates its native color pool resource.','Sample descriptor has count and quality; the proposed policy changes only a native exponent result, preserving quality/heap negotiation.'),
('117240','Reserves aligned depth heap space using the framebuffer sample descriptor and creates matching depth resources/descriptors.','Color/depth samples and heap offsets are coordinated resources, not independent scalar options.'),
('11b4f0','Creates/reuses format87 placed color resource at framebuffer heap offset144, sample descriptor160/164, then creates RTV. Creation path dereferences the resulting resource without a universal HRESULT/null rollback.','A native caller is not a proof of infallibility under OOM/device removal. Stay within native negotiated capability; no custom oversized allocation guarantee.'),
('11b290','Creates/reuses format20 placed depth resource at framebuffer heap offset152 with the same count/quality; creates a matching depth view.','Failure handling is incomplete as in the native color path. No separate depth-only sample control is established.'),
('1121d0','Before drawing, reads selected framebuffer sample count+160, encodes1/2/4/8 as PSO key bits27..28 and compares the full16-byte key before113590. It also applies dirty target/viewport/constant state.','No new shader binding or constant-layout change is needed for MSAA policy. Full1158-instruction ASM was recaptured in200-instruction pages after an initially misleading ten-line response.'),
('113590','Looks up/creates a PSO by the full16-byte packed key, retains/releases COM cache references and binds the selected PSO to the native command list.','Changing only a PSO sample count without matching attachments would violate the native key/resource relationship.'),
('117710','Decodes PSO sample exponent from keyDWORD0 bits27..28 using1/2/4/8; obtains shader blobs from552-byte program records, sets native solid rasterizer and creates the graphics PSO.','This proves sample-dependent PSO recreation; it does not establish a new wireframe or shader-replacement feature.'),
('1253d0','Selects direct shader-readable target reuse or transitions color/frame-texture resources and copies single-sample data versus resolves multisample data. Commands use the current native command-list context.','Raw attachment writes bypass resource-state and resolve decisions. The proposed policy leaves this consumer unchanged.'),
('121110','Marks draw/PSO/constant/texture state dirty at native recording boundaries, resets cached staging data when needed, and lets the next native draw rebuild state.','A trainer should not reproduce these dirty flags separately; normal begin/end paths already do so.'),
('119ba0','Native work facade can execute closures immediately, mark command-list boundaries and clone64-byte closure records for later replay, with context-dependent histories and C++ ownership.','It is not a simple asynchronous safe-call queue for arbitrary renderer operations. Call124FE0 request directly at the verified thread point instead.'),
('123990','Rotates the four deferred-release buckets underCS31352 and releases entries in the selected bucket, preserving renderer ownership sequencing.','Bucket rotation is frame-owned; no independent flush/GC action is specified.'),
('119a60','Queues old renderer objects in the current deferred-release bucket underCS31352;117FD0 uses it when replacing previous-frame texture.','No immediate-delete or universalframecount lifetime is exposed to a trainer.'),
('10a270','Constructs the in-situ presentation mutex atGX30848 and initializes resizeCS31432 plus other renderer critical sections before worker use.','Epoch and static address alone do not identify a live generation; use the application-thread shutdown-exclusion contract.'),
('10be40','Deletes resizeCS31432 and other critical sections, later destroys the presentation mutex and releases renderer resources/device references.','The lock storage cannot itself lease object lifetime. Do not lock after teardown merely because its address remains readable.'),
('11ad80','Requests application exit byApp+4752=256, joins/closes application handleGX784, then setsGX808 and joins/closes timing handleGX792.','A currently executing verified application callback finishes before native join completes. Unknown third-party destruction/reinitialization is outside this proof.'),
('127370','Shifts a64-float GPU-cost history and writes new float sample at index0.129180 feeds it with completed GPU timestamp-derived cost.','The policy wrapper should call original113B80 to preserve these temporal statistics rather than fabricate them.'),
('129180','Waits/maps completed query intervals, converts calibrated64-bit GPU timestamps using native float32 math, appends history and feeds127370 adaptive-cost samples.','The recorded signal is completed GPU work, not the current CPU frame. An override affects native policy without modifying measurement history.'),
]
claims=[]
for rva,finding,limit in findings:
    addr=f'0x{0x140000000+int(rva,16):x}'
    c=captures[addr]
    claims.append(dict(addr=addr,Finding=finding,Evidence=[c['evidence'],'work/trainer/research/renderer_round6_verification.json'],Limitations=limit,strength='full fresh ASM plus pseudocode/caller reasoning; original bytes verified'))
contract_text=(OUT/'renderer_round6_contract.txt').read_text(encoding='utf8')
contract=dict(status='static review proposal; not implemented or live tested',source_sha256=verification['source_sha256'],controls=[
 dict(name='Apply windowed resolution',feasibility='native request ready for guarded implementation',rva='0x124FE0',abi='void(void* GX,const float dimensions[2],int mode=0)',completion='queued, later actual-state observation',mutates_config=False),
 dict(name='Maximize game window',feasibility='native request ready for guarded implementation',rva='0x124FE0',abi='void(void* GX,const float dimensions[2],int mode=2)',mutates_config=False),
 dict(name='Exclusive fullscreen / loaded settings restore',feasibility='conditional: mode enumeration and disconnect edge must be addressed',rva='0x124FE0',mode=1,dependency='11C970 recursive empty-mode fallback'),
 dict(name='Fixed MSAA / maximum MSAA',feasibility='native resource/replay semantics closed; safe callsite-hook implementation still needed',site_rva='0x11A14F',original_target_rva='0x113B80',expected_hex='e82c9affff',return_rva='0x11A154',choices=[1,2,4,8],native_max='fresh max argument0..3; AMD max0 respected',auto_restore='pass through native policy; no direct resource restore')],
 narrative=contract_text,evidence_files=sorted({c['Evidence'][0] for c in claims}),limitations=['No process, UI, game, build, save or patch action performed.','No native allocation/device failure rollback guarantee.','Code-installation synchronization, unwind correctness and future runtime validation remain implementation work.'])
(OUT/'renderer_round6_contract.json').write_text(json.dumps(contract,indent=2)+'\n',encoding='utf8')
report=dict(title='Renderer round6: actual resolution and AA controls',scope='Only new research files; frozen0.10 untouched',session=verification['session'],source_sha256=verification['source_sha256'],summary='Windowed/maximized native requests are ready for guarded implementation. Actual fixed/capped MSAA has an identified normal-frame decision boundary preserving replay and resource creation, but needs a separately verified callsite-hook implementation. Fullscreen enumeration has an empty-set recursion edge.',capture_counts={k:verification[k] for k in ['function_count','instructions','function_bytes']},semantic_claims=len(claims),claims=claims,raw_support_only=sorted(set(captures)-{x['addr'] for x in claims}),contract='work/trainer/research/renderer_round6_contract.json',corrections=['113B80 cooldown/middle band checks current against max and returns min on excess. The unbounded return is1140EB->1145A1 when high current headroom fails the sustained-good history test. Universal-bound shorthand and preliminary cooldown explanation were corrected.','Dedicated disasm can return ten lines while claiming a complete1158-instruction body;1121D0 was recaptured using200-instruction pages and everycount/address/offset verified.'],boundaries=contract['limitations'])
(OUT/'renderer_round6_deep.json').write_text(json.dumps(report,indent=2)+'\n',encoding='utf8')
lines=[report['title'],'='*len(report['title']),report['summary'],'',f"Capture: {verification['function_count']} full bodies / {verification['instructions']} instructions / {verification['function_bytes']} original function bytes.",f"Semantic claims: {len(claims)}; remaining captured functions are raw support, not new semantic coverage.",'','Contract: renderer_round6_contract.txt/.json','']
for c in claims: lines += [c['addr'],c['Finding'],'Limit: '+c['Limitations'],'Evidence: '+c['Evidence'][0],'']
lines+=['Corrections']+['- '+x for x in report['corrections']]+['','No implementation, native call, live game, UI, build, EXE patch or IDB mutation in this round.']
(OUT/'renderer_round6_deep.txt').write_text('\n'.join(lines)+'\n',encoding='utf8')
paths=sorted(p for p in OUT.glob('renderer_round6*') if p.is_file() and p.name!='renderer_round6_checkpoint.json')
checkpoint=dict(status='research ready for independent review',source_sha256=verification['source_sha256'],counts=report['capture_counts'],claims=len(claims),files=[dict(path=str(p.relative_to(ROOT)).replace('\\','/'),sha256=hashlib.sha256(p.read_bytes()).hexdigest(),bytes=p.stat().st_size) for p in paths])
(OUT/'renderer_round6_checkpoint.json').write_text(json.dumps(checkpoint,indent=2)+'\n',encoding='utf8')
print(json.dumps(dict(claims=len(claims),capture=report['capture_counts'],artifacts=len(paths)),indent=2))
