<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><OutputType>Exe</OutputType><TargetFramework>net8.0-windows</TargetFramework><EnableDefaultCompileItems>false</EnableDefaultCompileItems></PropertyGroup><ItemGroup><Compile Include="Review.cs"/><Compile Include="../../../../src/KH2Trainer.Core/BdxInspection.cs" Link="BdxInspection.cs"/></ItemGroup></Project>
