"""Build this study's derived metadata. Does not touch the product or earlier studies."""
import json,hashlib,shutil
from pathlib import Path
from capstone import Cs,CS_ARCH_X86,CS_MODE_64
HERE=Path(__file__).resolve().parent
ROOT=HERE.parents[2]
BASE=0x140000000
def load(p):return json.loads(p.read_text(encoding='utf-8-sig'))
def put(name,value):(HERE/name).write_text(json.dumps(value,indent=2,ensure_ascii=False)+'\n',encoding='utf-8',newline='\n')
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
e=load(HERE/'evidence.json');cs=Cs(CS_ARCH_X86,CS_MODE_64)
e['code_ranges']=[]
for start,target in [(0x433510,0x3fb1c0),(0x433520,0x3fb4d0),(0x433830,0x3fb250)]:
 r=next(r for r in e['dataRegions'] if int(r['addr'],16)==BASE+start);raw=bytes(int(x,16) for x in r['data'].split());ins=list(cs.disasm(raw,BASE+start))
 e['code_ranges'].append({'addr':hex(BASE+start),'Domain':'native','size':len(raw),'end_exclusive':hex(BASE+start+len(raw)),'observed_line_count':len(ins),'originalBytes':r['data'],'tailTarget':hex(BASE+target),'asm':{'lines':[{'addr':hex(i.address),'instruction':i.mnemonic+' '+i.op_str} for i in ins]},'pagination':{'done':True,'instructionCount':len(ins)},'scope':'No IDA function definition; complete bounded original-code range decoded with Capstone from fresh IDA bytes. IDB unchanged.'})
put('evidence.json',e)
snapshots={}
for name in ['MissionFeatures.inl','MissionEventFeatures.inl']:
 src=ROOT/'src/KH2Trainer.Bridge'/name;dst=HERE/'source-snapshots'/name;dst.parent.mkdir(exist_ok=True);shutil.copyfile(src,dst)
 snapshots[dst.relative_to(HERE).as_posix()]={'sha256':sha(dst),'originalPath':src.relative_to(ROOT).as_posix(),'scope':'Read-only comparison snapshot; no new runtime path or proof of complete actor/resource lifetime.'}
put('source-snapshots.json',snapshots)
common='Native indexes are signed and unchecked; the constructor contains one timer, three counters, three gauges, one watch and one combo. Widget flag1 alone does not establish descriptor registration, HUD resource validity, active scene or lifetime. Threshold dispatch can synchronously reach scripts, Actors and transition handlers. This is an offline annotation, not a callable trainer contract.'
ann={}
def add(index,name,summary,helper,notes=''):
 row=e['rows'][index];kind='code_ranges' if index in [14,15,25] else 'functions'
 ann[f'4:{index}']={'handlerRva':row['handlerRva'],'declaredOperandCount':row['flags']&0xffff,'hasReturnSlot':bool(row['flags']&0x40000000),'name':name,'summary':summary,'notes':notes or common,'evidence':f'bdx-bank4-calls-20261008/evidence.json#{kind}[addr={hex(BASE+row["handlerRva"])}] + bdx-bank4-calls-20261008/evidence.json#functions[addr={hex(BASE+helper)}]'}
add(2,'Test result-context pointer','Returns whether global pointer RVA0x2A11478 is nonnull as @INT.',0x3ac220,'This tests pointer presence only; it does not validate the pointed object or its lifetime.')
add(3,'Begin mission result message7','Normally forwards operand0 to the mission result path as message7. For descriptor type30, a matching handler with a non-FFFF state condition can select message156 instead.',0x3a33c0,'The result path stops the timer, changes mission flags and may queue presentation phases or immediately dispatch and tear down the mission. Not a universal win primitive; downstream effects depend on current descriptors and handlers.')
add(5,'Set mission counter','Passes integer value operand0 and counter index operand1 to the clamping counter setter.',0x3fbae0)
add(6,'Increment mission counter','Adds1 to the counter selected by operand0, using DWORD addition before the clamping setter.',0x3fb2b0,common+' Signed overflow is not prevented: INT_MAX+1 becomes INT_MIN before clamping.')
add(7,'Restart mission timer','Uses seconds operand0 and timer index operand1. Positive seconds configure countdown; nonpositive seconds choose count-up using the widget maximum. Starts phase1 and clears pause bit2.',0x3fb9a0,common+' Seconds are multiplied by60 with DWORD arithmetic. Other pause bits and widget warning bit8 are preserved.')
add(8,'Set mission gauge','Passes float operand0 and gauge index operand1 to the absolute gauge setter. Any nonzero mission+1696 owner mask blocks this setter.',0x3fbcb0)
add(9,'Add to mission gauge','Adds float operand0 to the selected gauge. When global step717480<2, mission filename substrings can halve the delta before addition and the absolute setter.',0x3fb3a0,common+' PO01_MS501, TT12_WORK_BOX and HB32_FM_VEX halve it; TR04_MS104 does so for negative delta and TR07_MS203 otherwise; EH15_MS104 does so for delta>=-5. The tests are sequential; filenames and float comparisons matter. This is not a generic unscaled add.')
add(10,'Set normalized mission gauge','Multiplies float operand0 by the selected gauge signed-integer maximum, then calls the absolute setter.',0x3fbd90,common+' No finite/range validation occurs before the multiply; mission owner-mask gating still applies through the absolute setter.')
add(12,'Read normalized mission gauge','Returns selected gauge float current / float(signed maximum) as @FLT; returns0 when the mission/widget predicate fails.',0x3fb690,common+' No maximum-zero guard; division can produce NaN or infinity under masked floating-point exceptions.')
add(13,'Set timer pause bit2','ORs pause mask RVA0xABB854 with2.',0x157130,'Global App timer pause ownership is a bitmask. This neither allocates a trainer lease nor preserves independent owners through later lifecycle operations.')
add(14,'Restart registered mission widgets','When a mission exists, deactivates the registry first if mission flag1 is set, invokes vtable+16 for each registered widget lacking flag0x10, then sets mission flag1.',0x3fb1c0,common+' Timer activation restarts the global timer. Counter/gauge activation reaches HUD resources. The registry loop trusts the stored count.')
add(15,'Deactivate or suppress mission widgets','If mission flag1 is set, invokes registered widget vtable+24 and clears mission flag1. Otherwise sets mission flag2, which suppresses initial task activation.',0x3fb4d0)
add(16,'Begin mission result message16','Forwards operand0 through the current mission result path with message16.',0x3a3440,'No mission-null check in this immediate adapter/helper chain. The path can consume score helpers, stop the timer, enter presentation phases and dispatch transitions; it is not a reversible field update.')
for i,n,h in [(17,'timer',0x3fbe40),(18,'counter',0x3fbbf0),(19,'gauge',0x3fbd10),(51,'combo',0x3fba20)]:
 add(i,f'Configure mission {n}',f'Passes start operand0, maximum/flags operand1 and threshold operand2 to selected {n} vtable+48; index is operand3.',h,common+' A nonzero maximum replaces maximum after stripping bit30 and copies that bit into widget flag2; zero preserves both. Start/threshold always change. Counter/combo configuration also stores current=start; timer/gauge base configuration does not immediately store current.')
add(20,'Decrement mission counter','Adds-1 to the counter selected by operand0, using DWORD arithmetic before the clamping setter.',0x3fb2b0)
add(24,'Clear timer pause bit2','ANDs pause mask RVA0xABB854 with~2.',0x157110,'Other pause bits are retained. This is a raw bit clear, not an ownership-aware resume operation.')
add(25,'Add one mission combo','Adds1 to combo index0 and sets its float expiry allowance from operand0, forwarded in XMM1 then XMM2.',0x3fb250,common+' Current uses DWORD addition and clamp; a new peak can invoke threshold HUD behavior and raise the stored threshold. The allowance is decremented by global step717480 in the mission task, not by a proven wall-clock seconds unit.')
add(26,'Read mission timer ticks','Returns global timer value RVA0xABB860 when the selected timer passes the mission/widget predicate, otherwise0.',0x3fb790,common+' All indexed timer objects forward to the same global App timer value.')
add(27,'Reset current mission combo','For combo index0, clears expiry allowance, sets current=min(maximum,0), and clears flag8. Peak+80 is retained.',0x3fb910)
add(28,'Read normalized gauge threshold','Returns float(signed threshold) / float(signed maximum) for the selected gauge as @FLT, or0 when predicates fail.',0x3fb6f0,common+' Zero maximum is not rejected.')
add(29,'Read mission counter','Returns selected counter+56 as @INT, otherwise0 when predicates fail.',0x3fb640)
add(30,'Read mission combo peak','Returns combo index0 peak at+80 as @INT, otherwise0 when predicates fail.',0x3fb750)
add(31,'Read current mission combo','Returns combo index0 current at+56 as @INT, otherwise0 when predicates fail.',0x3fb600)
add(33,'Add mission combo amount','Adds integer operand0 to combo index0 and replaces float expiry allowance from operand1, forwarded through XMM1/XMM2.',0x3fb250,common+' Addition wraps DWORD before clamp. New peak updates can invoke threshold HUD behavior and raise threshold; no promise of seconds or safe infinite duration.')
add(34,'Test gauge threshold flag','Returns whether selected gauge flag8 is set, after mission/flag1 checks.',0x3fb8c0)
add(35,'Read record rank byte','Decodes operand0 pointer and returns its byte0 as @INT.',0x437c80,'The adapter itself performs the byte read. The related comparison helper treats byte0 as a rank. No null, provenance, bounds or lifetime check follows decoding.')
add(36,'Read record value','Decodes operand0 pointer and returns its DWORD+4 as @INT.',0x437c80,'The adapter itself performs the DWORD read. No null, provenance, bounds or lifetime check follows decoding; the field is compared unsigned by4:37.')
add(37,'Update ranked record if better','Decodes record operand0; compares rank operand1 and unsigned value operand2. Lower rank is rejected. Equal ranks4/6 accept a smaller value; equal other ranks accept a larger value. Accepted updates store byte0 and DWORD4 and return1; rejected updates return0.',0x437c80,'No pointer validation or input rank bound. A larger accepted rank is truncated to one byte on storage. No save-to-disk behavior is established by this helper.')
add(38,'Get global ranked record address','Returns encoded address RVA0x9AD664 + sign_extend(operand0)*8 as @ADR.',0x3e6690,'Index is unchecked. The helper establishes address arithmetic only; record count, valid runtime provenance and persistence are not proven here.')
add(39,'Set mission watch value','Writes integer operand0 to selected watch+64 using index operand1 after mission/flag1 checks.',0x3fbeb0,common+' Watch activation passes this field to the HUD helper. This setter does not restart the App timer.')
add(40,'Read rounded mission timer seconds','Returns uint32(timerTicks+59)/60 using DWORD wrap and unsigned division, tagged @INT for selected timer, or0 when predicates fail.',0x3fb7e0,common+' The MUL/SHR quotient is unsigned despite the @INT tag. For ticks=-60 the wrapped numerator is0xFFFFFFFF and the result is71582788. It rounds upward only within an appropriate nonnegative timer range; invalid/overflowed ticks must not be interpreted as real positive time.')
add(41,'Add mission counter amount','Adds integer operand0 to counter current using index operand1, then calls the native clamping setter.',0x3fb2b0,common+' DWORD overflow happens before clamp; no checked arithmetic.')
add(42,'Increment global record counter','Uses indices operand0/operand1 at pointer[0x750740]+3*operand0+operand1. Increments the byte only below99 and returns it. Also conditionally queues achievement147 when the rounded-timer helper result>0 and mission counter1 is zero.',0x406bf0,'Not a read-only query. The original pointer initializer is0x1409AD874. Indices are unchecked; preexisting bytes>=99 stay unchanged. Achievement latch79CAC5 bit8 is set even if achievement-context79CAC8 is null. No achievement delivery or save-file persistence is proven.')
add(43,'Raise mission combo peak','Raises selected combo peak+80 only when operand0 is greater, then performs threshold HUD handling and can raise a nonzero threshold to the new peak. Index is operand1.',0x3fbdf0,common+' Current and expiry allowance are not updated by this helper.')
for i,n,h in [(44,'counter',0x3fb510),(45,'watch',0x3fb5b0),(49,'timer',0x3fb560)]:
 add(i,f'Deactivate and inhibit mission {n}',f'For selected {n}, invokes vtable+24 if active flag4 is set, then sets flag0x10 so registry activation skips it.',h,common+' The action is more than hiding text: timer deactivation sets global pause bit2, and other widgets release/update HUD handles.')
add(46,'Set counter threshold helper id','Writes operand0 to selected counter+52 using index operand1.',0x3fbc60,common+' Threshold-on handlers call1DE0C0 with this nonzero field when active and flag8 was clear; the numeric ID domain is not validated here.')
add(47,'Set timer warning state','Calls selected timer vtable+32, reaching HUD warning behavior and setting flag8.',0x3fc030,common+' This does not itself expire the global timer or dispatch message74.')
add(48,'Replace mission counter decimal digit','For counter index operand2, computes DWORD10^operand0, replaces that signed-division decimal position using operand1, then calls the clamping counter setter.',0x3fbb30,common+' Position>=32 produces divisor0 after the counted loop and reaches IDIV with no guard. Negative position behaves as position0. Digits are not restricted to0..9; products/addition wrap. Conditional static fault path, not a demonstrated retail-script crash.')
add(50,'Set counter threshold state','If selected counter flag8 is clear, calls its vtable+32 threshold-on handler.',0x3fbf50)
add(52,'Set combo threshold state','If selected combo flag8 is clear, calls its vtable+32 threshold-on handler.',0x3fbf00)
add(53,'Set combo threshold helper id','Writes operand0 to selected combo+52 using index operand1.',0x3fba90)
add(54,'Set mission flag bit0','Calls the shared bit helper with selector0, setting bit0 in global RVA0x2A10500.',0x3a5810,'No ownership tracking. Paired4:55 is not restricted to this bit.')
add(55,'Test any mission flag','Calls the shared flag test with selector0. Selector0 returns whether any bit in global RVA0x2A10500 is nonzero, as @INT.',0x3a57f0,'It does not test only bit0 despite4:54 setting that bit.')
add(56,'Mark result context bit0x20','If global pointer RVA0x2A11478 is nonnull, ORs its first DWORD with0x20.',0x3abf10,'Presence is checked; pointee validity and lifetime are not established by this helper.')
add(57,'Set or clear gauge threshold state','Uses boolean operand0 and gauge index operand1 to invoke vtable+32 or+40 respectively after mission/flag1 checks.',0x3fbfd0,common+' Numeric gauge current is unchanged; HUD handlers and an optional1DE0C0 call are reachable.')
add(58,'Clear counter threshold state','If selected counter flag8 is set, calls its vtable+40 threshold-off handler.',0x3fbf50)
put('annotations.json',{'schema':1,'originalSha256':e['originalSha256'],'annotations':ann})
claims=[]
def claim(addr,text,helpers=(),extra=(),limit='Bounded static normal path. Not a complete transitive closure or runtime lifetime guarantee.'):
 refs=[f'evidence.json#functions[addr={hex(BASE+a)}]' for a in [addr,*helpers]]+list(extra)
 claims.append({'addr':hex(BASE+addr),'Finding':text,'Evidence':refs,'Limitations':limit})
claim(0x3a2c30,'Mission construction initializes one56-byte timer at+296, three80-byte counters at+352, three72-byte gauges at+592, one72-byte watch at+808, one88-byte combo at+880 and score at+1088. It builds msn/<language>/<name>.bar; original RTTI names corroborate these classes. The constructor sets base flag1 before descriptor registration.',[0x3a3fa0,0x3fa0b0,0x3fa610,0x3fac10],['verification.json'])
claim(0x3fc150,'Descriptor-driven widget registration calls reset+8 and configure+48, optionally resolves HUD data, appends at mission+976 and increments count+1048 without a capacity guard. Native index helpers likewise do not enforce the constructor counts.',[0x3fc210,0x3fc230,0x3fc290,0x3a31a0,0x3a3fd0])
claim(0x3fa410,'Base configuration always changes start+32 and threshold+40. A nonzero maximum clears input bit30 before storing maximum+36 and copies bit30 to widget flag2; zero preserves maximum and flag2. Counter/combo3FA440 additionally write current+56=start.',[0x3fa440,0x3fbe40,0x3fbbf0,0x3fbd10,0x3fba20])
claim(0x3fa230,'Counter zero/max crossings synchronously call3AABE0(14,id)/(123,id) only when old current crosses, id!=-1 and active flag4. Threshold virtual calls occur before the final current store. State can be affected by downstream callbacks before the saved widget is used again.',[0x3aabe0,0x3fa4c0,0x3fa1d0])
claim(0x3fa310,'Gauge zero/max crossings call3AABE0(136,id)/(137,id) before final float store under id/active checks. Integer-converted current drives threshold virtual calls. Absolute gauge setter rejects nonzero mission+1696, while raw configuration changes different fields.',[0x3fbcb0,0x3fbd10,0x3fa510,0x3fa200])
claim(0x3aabe0,'Messages14,74,123,136,137 take the default arm and synchronously call3F4980,3B4270,then3F60D0. The latter selects among16 96-byte records, prefers an exact parameter match over retained negative wildcard matches, applies3F61A0 and can enter transition/event helpers.',[0x3f60d0,0x3f6070,0x3f61a0],['verification.json'],'Dispatch/record boundaries established. Arbitrary script effects, Actor virtual handlers, heap/STATUS mutation and global drain safety are not closed by this study.')
claim(0x3fbb30,'4:48 computes10^position in DWORD arithmetic then uses signed IDIV without guarding zero. Every position>=32 has zero divisor if the loop completes. Negative positions skip the loop. Counter delta helpers and combo addition likewise wrap before clamping.',[0x3fb2b0,0x3fa790],['arithmetic-model.json'],'Conditional arithmetic result; no original-code execution, game crash observation, or retail script invoking an extreme position is established.')
claim(0x3fb3a0,'Gauge delta is selectively multiplied by0.5 for captured filename substrings when globalstep<2, before addition and absolute setter. Normalized setter multiplies signed maximum by input; normalized getters divide without maximum-zero guard.',[0x3fbd90,0x3fb690,0x3fb6f0],['verification.json'])
claim(0x3fa5d0,'Restart chooses countdown for positive seconds, count-up otherwise, starts phase1 and clears pause bit2. Activation uses the same global timer. Deactivation sets bit2 and clears widget active flag4. Timer vtable+32 sets warning8; +40 clears8.',[0x3f9ec0,0x3f9fe0,0x157140,0x157170,0x157190,0x157130,0x157110,0x3fa560,0x3a4620])
claim(0x1571b0,'The global App timer is blocked by any pause bit. Phase1 advances to2 without calculating a new value that invocation. Positive countdown expiry and configured count-up limit can set phase0 and dispatch74/0. Count-up values>215999 saturate and bypass the configured-limit test on that branch.',[0x3fb790,0x3fb7e0,0x3aabe0],'','Clock increments/OS-thread ownership and timer callback audience are separate research boundaries; message74 is not intrinsically mission failure.')
claim(0x3fa790,'Combo current+56 uses wrapped addition and signed clamp, peak+80 rises on a new high, threshold handling can raise nonzero threshold+40, and float allowance from XMM2 is stored at+84. Mission task calls3FA820, which subtracts globalstep and resets current/flag8 when a positive allowance expires; peak stays.',[0x3fb250,0x3fa820,0x3a35c0,0x3fa860,0x3fa8b0,0x3fa880],['evidence.json#code_ranges[addr=0x140433830]'])
claim(0x3a41e0,'Mission result handling performs score and1DE0C0 helpers, ORs missionflags0x14, stops the timer, changes global/HUD state and either dispatches immediately or stores pending message/parameter with phase2/4. The mission task progresses2->3->4 and can call3A3540; cleanup releases scripts/resources through helpers and nulls global mission pointer.',[0x3a33c0,0x3a3440,0x3a35c0,0x3a3540,0x3a3460,0x3a3800,0x3a37a0],'','Static storage is reused by3A3FA0, so pointer equality is not a generation. No universal success/failure or immediate-free claim, and no safe trainer outcome command is established.')
claim(0x437c80,'4:35/36 read decoded record byte0/DWORD4 without pointer checks;4:37 performs signed rank and unsigned value comparisons with inverse equal-rank preference for ranks4/6.4:38 returns unchecked9AD664+8*index. Larger accepted ranks truncate to byte.',[0x4338f0,0x433920,0x433950,0x4339a0,0x3e6690])
claim(0x406bf0,'4:42 increments a global byte at pointer[750740]+3*a0+a1 only below99; original pointer value is9AD874. It may enqueue achievement147 and latch bit8 when the rounded-timer helper result>0 and counter1==0. This is not a pure read.',[0x4339d0,0x0fee50,0x3fb7e0,0x3fb640],['verification.json'],'No index bounds, disk persistence, completed achievement delivery or retail triggering witness is established. The timer helper uses unsigned division after DWORD wrap, so a positive helper result alone does not prove valid positive elapsed/remaining time.')
claim(0x3a57f0,'Selector0 returns whether any supplied flag bit is nonzero.4:55 supplies selector0 and2A10500, whereas4:54 sets only bit0 using3A5810.',[0x3a5810,0x433560,0x433570])
for key,a in ann.items():
 idx=int(key.split(':')[1]);r=e['rows'][idx];refs=[x.replace('bdx-bank4-calls-20261008/','') for x in a['evidence'].split(' + ')]
 claims.append({'addr':hex(BASE+r['handlerRva']),'Finding':f'{key}: {a["name"]}. {a["summary"]}','Evidence':refs,'Limitations':a['notes']})
put('claims.json',{'schema':1,'Domain':'native','claims':claims})
report={'schema':1,'Domain':'native','title':'Bank4 mission widgets, result transitions and unsafe numeric adapters','originalSha256':e['originalSha256'],'scope':e['captureScope'],'structuralExtent':{'bank':4,'tableRva':0x757250,'records':59,'nullIndices':[0,1],'notNativeBounds':True},'findings':claims[:15],'annotations':len(ann),'trainerComparison':{'sources':'source-snapshots.json','existing':'MissionFeatures exposes guarded timer restart/snapshots. MissionEventFeatures slots230..232 use3FBAE0/3FBCB0/3FA230 with bounded indexes, finite/range checks, registered widget/vtable/HUD checks, code-byte checks, scene/heartbeat checks, fresh revalidation and boundary-event preflight. This study adds no runtime path.','proposed':'Later: checked relative/decimal counter action, with int64 arithmetic on the freshly validated current value, position0..9 and digit0..9, reject values outside0..min(max,INT_MAX), then reuse the existing absolute setter/event gates exactly once. Never call4:48 or unchecked3FB2B0 directly. Required semantics: reject an invalid argument/result rather than silently clamp; preserve request receipts and uncertain-write policy.','secondaryProposal':'Read-only combo current/peak/expiry allowance display, verifying registration/vtable and mission context first. Label allowance in native update units until unit conversion and pause ownership are proven. No always-on freeze, mission-win button or raw pause-bit ownership claim.'},'openBoundaries':['No retail script census or malformed operand witness in this study.','Callback dispatch is synchronous in these native bodies, but arbitrary handlers, script/Actor effects and bulk teardown remain separate lifetime proofs.','Static mission address reuse and baseflag1 are insufficient readiness/generation checks.','Original RTTI names establish captured class metadata; no type-safe dynamic cast or global object census follows.','Positive IDB xrefs are original-byte verified; missing xrefs are not evidence of absent reachability.','Selected data-record changes are in memory; no save-file flush semantics or valid record-array extent is inferred.','Existing Bridge gates are a compared implementation, not newly certified global drain safety.']}
put('report.json',report)
lines=['BDX BANK4: MISSION WIDGETS AND RESULT LIFECYCLE','',f'Original SHA256: {e["originalSha256"]}','Scope: '+e['captureScope'],'','Bank4 has59 captured structural records, two NULL holes,54 defined adapter bodies and three separate branch code ranges.4:21 already has an annotation in the frozen timer study; it is not replaced here. The recorded extent is not a native bounds check.','', '1. COHERENT SUBSYSTEM']
for i,c in enumerate(claims[:15],1):lines.extend(['',f'{i}. {c["addr"]}: {c["Finding"]}','Evidence: '+'; '.join(c['Evidence']),'Limit: '+c['Limitations']])
lines.extend(['','2. TRAINER COMPARISON AND CONCRETE PROPOSAL',report['trainerComparison']['existing'],report['trainerComparison']['proposed'],report['trainerComparison']['secondaryProposal'],'','3. LIMITS',*report['openBoundaries'],'','4. REPRODUCTION','py -3 -B docs/research/bdx-bank4-calls-20261008/verify.py --check','Optional: --exe <same-SHA original executable>. Requires capstone. No target code is executed.','Read evidence.json for complete paginated ASM, pseudocode and original bytes; code_ranges are deliberately not IDA function definitions. source-snapshots pins the compared Bridge state. arithmetic-model.json is only a DWORD arithmetic model.'])
(HERE/'report.txt').write_text('\n'.join(lines)+'\n',encoding='utf-8',newline='\n')
print(json.dumps({'functions':len(e['functions']),'codeRanges':len(e['code_ranges']),'annotations':len(ann),'claims':len(claims)}))
