"""Build bounded claims and human-readable report from the frozen evidence."""
from pathlib import Path
import json
HERE=Path(__file__).resolve().parent
ev=json.loads((HERE/'evidence.json').read_text());claims=[]
def claim(addr,title,finding,refs):
    claims.append({'addr':'0x140'+addr.lower(),'Title':title,'Finding':finding,'Evidence':[('evidence.json#functions[addr=0x140'+r.lower()+']') if all(ch in '0123456789abcdefABCDEF' for ch in r) else r for r in refs]})
claim('127100','Concrete callback slot and setter','127100 gets singleton 8A0970 through 11C150, returns the old device+728 pointer and stores the supplied pointer with plain loads/stores at 127111/127118. Its concrete named caller is tail wrapper 15EF60. This setter does not acknowledge or drain an already loaded callback; original slot address is 8A0C48. This is a proven binding, not an alias-complete writer census.',['127100','11c150','15ef60'])
claim('109F50','Constructor initialization','10A270 passes device+8 into 109F50. The latter writes zero at this+720 (10A25B), therefore device+728 starts NULL. 10A270 also initializes device+760 to -1, so the tick-work gate is initially enabled. 10D600 contains the same guarded singleton initialization sequence as 11C150, not an unconditional replacement of an existing initialized singleton.',['109f50','10a270','11c150','10d600'])
claim('154440','Actual registered target and ordering','App initialization 14ED40 calls 1532A0, which calls 154440. This routine initializes counters, registers task 1571B0 via 157090, publishes function 154700 through 15EF60 at 154495, then initializes semaphore state through 15ED70 at 15449A and registers task 1548E0. Publication precedes semaphore initialization. The callback has an explicit NULL-semaphore path; this ordering alone is not proof of a crash or a harmful retail interleaving.',['154440','1532a0','14ed40','157090','15ed70','15edb0'])
claim('1287D0','Timing-worker call context and pause boundary','11D0A0 creates separate App127ED0 and timing129110 threads through _beginthreadex; timing is created suspended then resumed. 129110 calls 1287D0. The optional call at 128C4D loads device+728 and passes zero in RCX; its result is ignored. It is reached only through the nonzero device+760 and accumulated-tick conditions, after signaling device+768. It precedes the device+776 pause read at128E01. Pause request stores alone therefore do not prove callback quiescence. The observed pause loop stops further callback iterations until resume/stop, but exposes no caller-visible acknowledgement.',['11d0a0','127ed0','129110','1287d0','127eb0','125a10'])
claim('154700','Immediate callback closure and ABI','The actual installed target154700 ignores its incoming argument, calls1574E0,1570F0,15EDB0, increments ABAC00/04 with ordinary load/inc/store operations, and returns EAX=0. The complete immediate normal-control-flow closure is154700,1574E0,152380,1570F0,15EDB0 plus the shared0FDB10 tail and fixed ReleaseSemaphore import. There is no Actor/STATUS call, vtable dispatch, asset-resource mutation, or application-supplied nested callback in that closed path. These bytes establish the observed x64 ABI behavior, not an exact recovered C++ source typedef or exclusivity for future callback replacements.',['154700','1574e0','152380','1570f0','15edb0','evidence.json'])
claim('1574E0','Global save-buffer counters are written by timing worker','152380 returns fixed global buffer9A98B0. 1574E0 increments unsigned DWORD+0x2444 when below0x0CDFE5C4 and always writes it back; it reloads and writes back DWORD+0x2448 unchanged. If716884 is nonzero and zero-extended byte717008 is in0..18, it similarly saturates DWORD+0x244C+4*index. The signed comparison against-1 after MOVZX cannot reject any zero-extended byte; the upper bound excludes0xFF. These stores mutate resident save-buffer memory, not a save file, and use no atomic update. Playtime-style counter semantics are an interpretation of the timing cadence; exact UI time units and save serialization are outside this study.',['1574e0','152380'])
claim('1570F0','Timing gate separate from renderer pause','1570F0 increments ABB850 only while DWORD ABB854 is zero. 157110 clears requested bits with AND-not; 157130 sets requested bits with OR. This counter gate does not gate154700\'s ABAC00/04 or1574E0 buffer writes and is distinct from device+776. These are ordinary shared-memory operations; no global lifetime barrier follows from them.',['1570f0','157110','157130','154700'])
claim('15EDB0','Waiter-gated semaphore signal','15EDB0 loads ABC610, returns without dereference when NULL, otherwise branches to shared tail0FDB10. The tail calls ReleaseSemaphore(handle,1,NULL) only when wrapper DWORD0 is nonzero; the handle is at wrapper+8. 15ED70 creates this wrapper with initial count0 and maximum1. It is a wake-up path for existing waiters, not an unbounded accumulated tick count. The full out-of-line tail is preserved separately because IDA entrypoint pagination alone lists only the four primary instructions.',['15edb0','15ed70','0fd9c0','evidence.json'])
claim('0FDD90','Wait and failure behavior','0FDD90 increments wrapper DWORD0 with LOCK INC, waits on handle+8 with INFINITE, then LOCK DECs the count even when WaitForSingleObject returns failure. 0FD9C0 returns NULL on allocation failure, but does not reject a NULL CreateSemaphoreA handle after successful allocation. 15EE10 skips the main wait for a NULL wrapper. Release/wait status is not converted to a recovery protocol by154700/1548E0. A waiter counter is not an ownership pin for arbitrary actors or buffers.',['0fdd90','0fd9c0','15ee10','154700','1548e0'])
claim('1548E0','App consumer remains separate from timing callback','1548E0 is a separately registered root9BA888 task. It performs rendering-related calls, waits via15EE10, computes scaled/unscaled frame delta with a6.0 upper clamp, writes reciprocal delta, and resets ABAC04. 15EE10 waits on ABC610 if present, then signals non-NULL handles at ABC5C8 and ABC5F8 through0FDC70. Neither the callback nor this semaphore API executes1548E0 inline; scheduler registration/dispatch is documented in the pinned actor-task study. Full transitive rendering/resource closure is intentionally not claimed here.',['1548e0','154440','15ee10','0fdc70','../actor-task-context-20261008/evidence.json#functions[addr=0x14014F770]','../actor-task-context-20261008/evidence.json#functions[addr=0x14014FC20]'])
claim('1571B0','Downstream timer completion reaches dynamic app dispatch','157090 separately registers1571B0. Under its state/count conditions1571B0 calls3AABE0(74,0). Original switch selector data in3AABE0 maps74 to the default dispatch arm, which calls3B4270. 3B4270 iterates3BF4F0 results, decodes each entry\'s pointer, and invokes virtual slot+96. This is a concrete downstream dynamic target boundary on the App task path. The immediate timing callback does not enter it; actual handler instances and transitive mutation effects are not closed by this study.',['157090','1571b0','3aabe0','3b4270','../actor-task-context-20261008/evidence.json#functions[addr=0x14014F770]'])
claim('11AD80','Normal closure uses thread stop/join rather than callback withdrawal','11AD80 requests App exit, polls the App thread handle until GetExitCodeThread no longer reports259, closes it, then sets timing stop device+808, polls/closes the timing handle, and releases device+768. It does not first unregister device+728. During the App-wait interval the timing callback can still be reachable. 1287D0 exits its loop after observing+808 and cleans its timer/event. Poll errors and an infinite GPU wait remain limitations of the existing closure, as in the frozen App study; a pointer replacement is not equivalent to successful thread completion.',['11ad80','1287d0','127100'])
claim('10BE40','Destructor and semaphore ownership boundary','10BE40 destroys graphics members and closes stored thread handles if non-NULL; its captured body neither waits for those threads nor clears device+728. The normal stop/poll sequence is11AD80. The four named ABC610 references are initializer store, callback load, consumer load, and572740\'s address setup. 572740 subtracts48 twice and calls no-op16C950 on ABC5E0/ABC5B0; it does not dereference or free ABC610. No lifetime cleanup guarantee for that wrapper follows from this named-reference census; alias writes/frees are not excluded.',['10be40','11ad80','572280','572740','16c950','evidence.json'])
claim('127100','Writer census limits and trainer consequence','The saved IDA listing search over executable heads in[140001000,140580000) found88 literal+2D0/+2D8 displacement hits. Together with complete named incoming-reference snapshots this locates the concrete singleton constructor, setter and invocation. Equal offsets on other object types, rebased pointers, bulk writes, unrecognized code and dynamic stores prevent an exclusive-writer conclusion. A trainer must treat callback replacement, scene lifetime, resident save writes and actor ownership as separate synchronization problems. No runtime hook or product patch is licensed by this study alone.',['127100','109f50','1287d0','evidence.json'])
def dump(path,obj):path.write_text(json.dumps(obj,indent=2)+'\n',encoding='utf-8')
dump(HERE/'claims.json',{'schemaVersion':1,'Domain':'native','claims':claims})
limits=[
 'Static retail analysis only; no game execution, live attachment, UI, injection, save-file write or IDB mutation.',
 'The immediate registered callback has a closed normal call graph. App consumers, GX destructor virtual releases, OS internals and exceptional runtime scheduling do not have a whole-program closure here.',
 'A zero original slot/global and a guarded singleton constructor establish initial image state, not a guarantee that arbitrary later aliases preserve it.',
 'Original xrefs are corroborated against file bytes; no absence-of-xrefs argument is used to prove exclusive thread ownership or free safety.',
 'The App-thread registration and timing-thread call are separate contexts. No exclusive OS-thread ownership is inferred from names or callback addresses.',
 'No observed crash, lost-tick defect, callback replacement race, save corruption, retail deadlock, or memory leak is claimed. Error return handling and possible ordering boundaries are stated as native behavior.',
 'Named constructors/destructors have full primary-body pagination; unrelated C++ exception funclets are not claimed as separately reviewed cleanup bodies.',
 'The switch table in3AABE0 occupies132 embedded data bytes in its560-byte IDA extent; it is verified as data, not counted as instructions.'
]
report={'schemaVersion':1,'Domain':'native','date':'2026-10-08','status':'BOUNDED_STATIC_CALLBACK_CLOSURE','subject':'GX device+728 timing callback, concrete target154700, separate App consumers and normal closure','originalSha256':ev['originalSha256'],'summary':'The installed callback updates resident save-buffer counters and timing counters, then conditionally signals a waiter semaphore. Its immediate closure contains no Actor/STATUS/asset-resource dispatch. A separate App timer task reaches a virtual dispatcher; pause and callback replacement are not lifetime barriers.','freshFunctions':32,'reusedFunctions':9,'fullPrimaryBodies':41,'sharedTail':{'addr':'0x1400fdb10','owner':'0x14015edb0','instructions':8,'bytes':25},'claims':claims,'limits':limits,'reproduce':['py -3 -B docs/research/timing-callback-context-20261008/verify.py --check','Optional evidence rebuild: py -3 -B docs/research/timing-callback-context-20261008/prepare_evidence.py (writes only this study)'],'dependencies':ev['dependencies']}
dump(HERE/'report.json',report)
lines=['Timing-Callback: konkrete Bindung und Ausführungskontext','======================================================','Stand: 2026-10-08; ausschließlich statische Retail-Belege.','',report['summary'],'','Belegte Kette','-------------','App-Thread: 127ED0 → 121D90 → App-init14ED40 → 1532A0 → 154440 → 15EF60 → 127100 → singleton8A0970+728 =154700.','Timing-Thread: 129110 → 1287D0 → optionaler CALL128C4D → 154700 → Savebuffer-Zähler / Timing-Zähler / wartende Semaphore.','Separate App-Aufgaben: 1571B0 kann über3AABE0(74,0) zu virtueller Dispatch-Grenze3B4270 gelangen;1548E0 wartet auf den Timing-Impuls und berechnet das Frame-Delta.','','Befunde','-------']
for n,c in enumerate(claims,1):lines.extend([str(n)+'. '+c['Title']+' ['+c['addr']+']',c['Finding'],'Evidence: '+'; '.join(c['Evidence']),''])
lines.extend(['Nutzen für Trainer','------------------','Die Kette eignet sich als dokumentierte Quelle für die tatsächliche Tick-Fortschreibung und als Orientierung für reine Beobachtung der Timing-Zähler. Ein gleichmäßiger Timing-Impuls ist kein Beweis für eine stabile Spielszene. Insbesondere müssen Änderungen am Savebuffer berücksichtigen, dass der Timingworker selbst dort schreibt. Actor-/STATUS-Transaktionen brauchen weiterhin die belegte Bindungs- und Lebensdauergrenze.','Ein Callback-Austausch über127100 gibt lediglich den alten Pointer zurück; ein bereits geladener Pointer kann weiter ausgeführt werden. Ein sicheres Installations-/Drain-Protokoll ist durch diesen Setter nicht implementiert.','','Grenzen','-------'])
lines.extend('- '+x for x in limits)
lines.extend(['','Reproduktion','------------']+report['reproduce']+['','Artefakte: evidence.json enthält vollständige paginierte ASM, Pseudocode, Original-/IDA-Bytes, Importidentitäten, Xrefs, Initialbilddaten und Such-Snapshots. native-listings.txt ist die lesbare Fassung. verification.json und manifest.json sichern den Stand.'])
(HERE/'report.txt').write_text('\n'.join(lines)+'\n',encoding='utf-8')
print(json.dumps({'claims':len(claims),'references':sum(len(c['Evidence']) for c in claims)}))
