"""Generate reviewed, bounded names for 27 captured bank-0 adapters."""
import json
from pathlib import Path
HERE=Path(__file__).resolve().parent
def load(p):return json.loads(p.read_text(encoding='utf-8-sig'))
def write(p,x):p.write_text(json.dumps(x,ensure_ascii=False,indent=2)+'\n',encoding='utf-8')
ann={}
def a(i,name,summary,notes):
 ann[f'0:{i}']={'name':name,'summary':summary,'notes':notes,'evidence':'bdx-object-calls-20261008: imported-evidence.json, evidence.json, extended-evidence.json, support-evidence.json, effect-update-evidence.json, verification.json'}
ptr='Encoded pointers require valid native objects and live storage; the adapter does not validate their type or lifetime.'
nan='The adapter replaces NaN components of the referenced input vector(s) with zero in place. '
effect='Operand 0 encodes a ryj::EFFECT object; its QWORD +48 points to the child effect state. A missing child is not guarded. '
a(13,'Rotate vector around Y','Rotates operand 0 by float operand 1 in radians around Y. Returns @ADR to shared storage at RVA 0x2AEA7F8.',nan+'The angle passes through 0x3B6F20 before the matrix rotation. The full four-component vector is transformed; later calls overwrite the result. '+ptr)
a(68,'Rotate vector around X','Rotates operand 0 by float operand 1 in radians around X. Returns @ADR to shared storage at RVA 0x7535C8.',nan+'The angle passes through 0x3B6F20; the buffer is shared with other vector calls. The decompiler omits the third native argument in XMM2. '+ptr)
for i,offset,name in [(38,0,'position'),(39,32,'scale'),(40,16,'rotation')]:
 a(i,'Set effect '+name+' vector',f'Copies all four float components of operand 1 into the child effect state at byte offset {offset}. No VM return slot.',effect+nan+('Rotation components are radians. ' if i==40 else '')+ptr)
a(41,'Set effect direction','Converts direction operand 1 to (atan2(-y, sqrt(x*x+z*z)), atan2(x,z), 0, 1) and copies it to the child rotation vector at +16.',effect+nan+ptr)
a(44,'Set effect child flag +145','Writes 1 to BYTE +145 of the child pointed to by effect QWORD +48. No VM return slot.',effect+'The apparent preliminary null test does not prevent the final call with a null effect. This observation does not establish all consumers of the child flag. '+ptr)
a(85,'Set effect child flag and owner bit','Sets bit 0 of the effect DWORD +12, then writes 1 to child BYTE +145. No VM return slot.',effect+'No successful null guard is present. Full downstream flag semantics are not established. '+ptr)
a(49,'Read effect active flag','Returns @INT 1 when bit 0x10000 in effect DWORD +12 is clear, otherwise 0.','This reads a flag only; it does not prove child availability, allocation validity or future effect lifetime. '+ptr)
a(50,'Read effect child presence','Returns @INT 1 when effect QWORD +48 is nonzero, otherwise 0.','The child is not dereferenced by this test, and a nonzero pointer is not validated. '+ptr)
a(51,'Stop and release effect child','Sets effect DWORD +12 bits 0x10001. If QWORD +48 is nonzero, runs the child cleanup and release paths, then clears that pointer.','Cleanup reaches component callbacks, reference-count changes and the effect allocator. It does not destroy the enclosing ryj::EFFECT in this helper. '+ptr)
a(52,'Fade and release effect child','Operand 1 is a float duration in native tick-factor units. A positive ordered value sets bit 0x20000 and stores -(effectFloat56 / duration) at +60. Operand 2 also sets owner bit 0 when nonzero.','Nonpositive or unordered duration takes the immediate child cleanup/release branch (with masked floating-point exceptions). Update path 0x2BD190 applies slope * global 0x717480 to +56, scales child vector +48 component w and releases at zero under its update gates. No seconds conversion is established. '+ptr)
a(53,'Read effect position','Copies the child vector at +0 to shared storage RVA 0x2AEA810 and returns its encoded address as @ADR.',effect+'All four components are copied without NaN sanitization. A later call overwrites the result. '+ptr)
a(54,'Read effect forward direction','Builds a matrix from child rotation xyz, applying X then Y then Z rotations, and transforms the constant (0,0,1,0). Returns @ADR to shared storage RVA 0x2AEA840.',effect+'Angles are radians; the helper wraps each with repeated float additions/subtractions of 2*pi. Infinite or sufficiently large finite angles can make those loops fail to progress. Rotation data is not sanitized here. '+ptr)
a(66,'Set effect update flag','Sets or clears bit 0x200000 of effect DWORD +12 according to operand 1 != 0.','The update path combines this with other flags and writes child BYTE +193, which gates at least the child delay countdown. This is not a proof that all effect activity pauses. '+ptr)
a(67,'Set effect vector +48','Copies all four float components of operand 1 to child byte offset 48. No VM return slot.',effect+nan+'The owner fade path multiplies the w component of this child vector. The remaining downstream color/render consumers are outside this bounded claim. '+ptr)
a(79,'Register effect in four-slot ring','For a nonnull effect, replaces the pointer selected by global index RVA 0x2AE7558 in the four-QWORD array at 0x2AE7538. The previous nonnull effect receives a fade/release request with duration 4.0 and owner bit 0 set.','The index advances with signed remainder modulo 4; normal ring indices are 0..3. No index-range guard or ownership pin is added. A null operand is a no-op. '+ptr)
a(46,'Turn direction toward vector','Normalizes local xyz copies of operands 0 and 1, computes their angle and cross-product axis, then rotates the first direction. For finite nonnegative operand2 * tickFactor, the rotation angle is min(angle, operand2 * tickFactor). It sets the local direction w to zero before the matrix transform, then copies the result into operand 0.',nan+'The native float operand 2 is passed in XMM3; tickFactor is global 0x717480. Zero and antiparallel vectors have no special axis fallback, so intermediate results need not remain unit length. Negative and nonfinite inputs follow the raw COMISS/MAXSS branches. '+ptr)
a(83,'Rotate vector around axis','Rotates vector operand 0 around the normalized xyz axis in operand 1 by float operand 2 in radians. Returns @ADR to shared storage RVA 0x7535C8.',nan+'The angle is wrapped by 0x3B6F20. The full four-component vector is transformed. A zero axis has no special fallback and does not generally produce an identity rotation. '+ptr)
a(90,'Build and discard local transform','Declares five operands, but reads only operand 0 as a vector address and operand 1 as a scalar. It builds a uniformly scaled matrix on the native stack, then copies the sanitized vector into that matrix\'s translation column. No VM return slot.','The completed local matrix is discarded; no drawing or external matrix publication is present in this captured path. NaN sanitization still writes zero into the referenced input vector. Declared operands 2..4 are consumed by the VM but unused by this adapter. '+ptr)
a(61,'Get character save record','Maps character IDs 1..15 to the resident save table at RVA 0x9ABDA0 and returns @ADR. IDs 14 and 15 alias records 1 and 6; other valid IDs map directly. Record stride is 276 bytes.','An out-of-range ID yields an encoded null address. A returned pointer allows later native writes; it does not allocate or copy a record.')
a(62,'Set character item-slot count','Changes BYTE +18 of the record addressed by operand 0 to the low byte of operand 1. Increasing the signed count clears corresponding WORD entries at +52 and +68; decreasing it returns nonzero +52 entries through 0x3C3F00(item,100,0) and clears those slots.','The loop uses the full signed operand while the stored count is a byte. No capacity, negative-count, record-type or null guard exists. The inventory grant path has additional side effects and failure behavior. '+ptr)
a(75,'Set character weapon IDs','Uses operand 0 as a character ID and writes low WORDs of operands 1 and 2 to offsets 0 and 2 of that save record. The native weapon selector reads these fields by hand index outside its Sora form-offhand special case.','IDs 14 and 15 alias records 1 and 6. Invalid IDs reach null-address stores. No item, ownership, model or status-rebuild validation is performed by this adapter.')
a(76,'Set Drive Form Keyblade','Uses operand 0 as a form-record index 1..10 and writes the low WORD of operand 1 to that record at RVA 0x9ABDA0 + 3588 + 56*(index-1).','The native Sora offhand selector reads this field for Drive Forms. An invalid form index reaches a null store; item existence, Keyblade type, unlock, ownership and model availability are not checked. This direct script operation does not include the trainer\'s validated fallback.')
a(98,'Add equipped Drive ability','Scans 24 WORDs at form-record +8 for the first entry whose low 15 bits are zero. Writes lowWORD(operand1) | 0x8000 there. Operand 0 selects form record 1..10.','A full array is left unchanged. Invalid form indices can fault through a null record. No duplicate, ability-ID or ownership check occurs. The native helper returns a slot index, but this descriptor has no VM return slot.')
a(99,'Add character ability','Scans 80 WORDs at decoded operand0 +84 for the first entry with low 15 bits zero. Writes (lowWORD(operand1) & 0x7fff), with bit 15 set when operand 2 is nonzero.','A full array is left unchanged. No duplicate, ability-ID, capacity expansion or record-type validation occurs. The helper\'s slot index is discarded by the no-return descriptor. '+ptr)
a(74,'Create cached layout','Decodes operand 0 as a resource name, allocates and initializes a 256-byte dk::CacheBuffLayout, obtains its cached resource and passes operand 1 to the layout setup with fixed value 4800.','The native object pointer is not returned to the VM. Allocation/resource validity and the meaning of the option value are not checked by this adapter; transitive layout ownership and rendering behavior remain outside this bounded claim. '+ptr)
rows=load(HERE/'imported-evidence.json')['descriptors']
assert len(ann)==len(rows)==27
for r in rows:
 e=ann[f"0:{r['index']}"];e.update(handlerRva=r['handlerRva'],declaredOperandCount=r['flags']&65535,hasReturnSlot=bool(r['flags']&0x40000000))
write(HERE/'annotations.json',dict(sorted(ann.items(),key=lambda x:int(x[0].split(':')[1]))))
claims=[]
for r in rows:
 e=ann[f"0:{r['index']}"]
 claims.append({'addr':hex(0x140000000+r['handlerRva']),'Finding':f"Native descriptor 0:{r['index']} ({e['name']}): {e['summary']}",'Evidence':['imported-evidence.json','evidence.json','extended-evidence.json','support-evidence.json','effect-update-evidence.json','vector-scale-evidence.json','additional-bytes.json','verification.json','annotations.json'],'Limitations':e['notes']+' Bounded original-file claim; no live-game execution.'})
write(HERE/'claims.json',{'Domain':'native','claims':claims})
print({'annotations':len(ann),'claims':len(claims)})
